### ISSUE TITLE
Failed assertion: line 108 pos 12: '_positions.length == 1'

### ISSUE THREAD

**Issue by raindy29** [ted-marozzi/sync-scroll-controller#1]
If  load  data in Listview , An error occurred

ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 108 pos 12: '_positions.length == 1'

#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:108:12)
#3      _SyncScrollController.position (package:yami_grid/src/sync_scroll_controller.dart:171:45)
#4      _SyncScrollPosition.hold (package:yami_grid/src/sync_scroll_controller.dart:225:18)
#5      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:655:22)

**Comment by ted-marozzi** [comment]
Hey,
Could you please share a repo that demonstrates this issue please?
Thanks.
